import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Read the data generated by the C++ engine
data = pd.read_csv('build/euler_convergence.csv')

dt = data['dt']
strong_err = data['strong_error']
weak_err = data['weak_error']

plt.figure(figsize=(10, 6))

# Plot the actual data on a log-log scale
plt.loglog(dt, strong_err, 'bo-', label='Measured Strong Error')
plt.loglog(dt, weak_err, 'ro-', label='Measured Weak Error')

# Plot theoretical reference lines
# We offset the reference lines slightly so they don't cover the data points
ref_dt = np.array([dt.min(), dt.max()])
plt.loglog(ref_dt, 2.0 * ref_dt**0.5, 'b--', label='Theoretical Strong Order (0.5)')
plt.loglog(ref_dt, 2.0 * ref_dt**1.0, 'r--', label='Theoretical Weak Order (1.0)')

plt.xlabel('Time Step Size (dt)')
plt.ylabel('Error')
plt.title('Euler-Maruyama Convergence Rates')
plt.legend()
plt.grid(True, which="both", ls="--", alpha=0.5)

# Invert x-axis so smaller dt is on the right (higher resolution)
plt.gca().invert_xaxis()

# Save the figure directly for Overleaf
plt.savefig('euler_convergence_plot.png', dpi=300, bbox_inches='tight')
print("Saved euler_convergence_plot.png")