import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load the data generated by the C++ code
# Ensure this script is run from the project root, or update the path
data = pd.read_csv('build/paley_wiener_paths.csv')

t = data['t']
M_values = ['M=1', 'M=2', 'M=5', 'M=10', 'M=50', 'M=200']

# Create a 2x3 grid of subplots
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
fig.suptitle('Paley-Wiener Representation of Brownian Motion', fontsize=16)

# Plot each M value on its respective subplot
for i, ax in enumerate(axes.flatten()):
    if i < len(M_values):
        col_name = M_values[i]
        ax.plot(t, data[col_name], color='blue', linewidth=1)
        
        # Format the subplot to match the paper's style
        ax.set_title(col_name)
        ax.set_xlim(0, 2 * np.pi)
        
        # Set x-ticks to 0 and 2*pi
        ax.set_xticks([0, 2 * np.pi])
        ax.set_xticklabels(['0', '2*pi'])
        
        # Determine appropriate y-limits based on data
        min_y = data[col_name].min()
        max_y = data[col_name].max()
        # Add some padding
        padding = (max_y - min_y) * 0.1
        ax.set_ylim(min_y - padding, max_y + padding)
        
    else:
        # Hide any unused subplots
        ax.axis('off')

plt.tight_layout()
plt.subplots_adjust(top=0.9) # Adjust to fit the main title
plt.show()
# plt.savefig('paley_wiener_plot.png', dpi=300, bbox_inches='tight')
# print("Saved paley_wiener_plot.png")